### ISSUE TITLE
Confusing error when Tranco lists are down

### ISSUE THREAD

**Issue by ghostwords** [DistriNet/tranco-python-package#3]
Looks like the lists are down at this time (I get "502 Bad Gateway" from the download button on https://tranco-list.eu/).

One then gets a pretty confusing stack trace from the Tranco package:
```python
>>> from tranco import Tranco
>>> t = Tranco(cache=False)
>>> tranco_list = t.list()
Traceback (most recent call last):
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 685, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 689, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/tranco/tranco.py", line 56, in list
    top_list_text = self._download_zip_file(list_id)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/tranco/tranco.py", line 81, in _download_zip_file
    r2 = requests.get(download_url)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/USER/.virtualenvs/VENV/lib/python3.5/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by ghostwords** [comment]
Clarification, not all lists are down, just the latest:

```python
>>> from tranco import Tranco
>>> t = Tranco(cache=False)
>>> tranco_list = t.list(date='2020-02-18')
>>> len(tranco_list.top())
1000000
>>> tranco_list = t.list(date='2020-02-19')
Traceback (most recent call last):
...
```

**Comment by VictorLeP** [comment]
Thanks for the report!

The list was not correctly generated today due to a full disk. I've cleared some space, put the database back in a correct state, and today's list is currently being regenerated. In any case, the issue should be resolved tomorrow.

I'll look into the confusing errors separately, at a later date.

Victor

**Comment by VictorLeP** [comment]
Confirming that the list was properly generated today.
